name: Build and Deploy Django Distill

on:
  push:
    branches:
      - master  # Trigger the workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: |
        poetry install

    - name: Pre-create output directory
      run: |
        mkdir -p dist

    - name: Build static files
      run: |
        poetry run python manage.py collectstatic --noinput
        yes | poetry run python manage.py distill-local dist


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  
        publish_branch: gh-pages 
